//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.BulkInsert.Test.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.Authors = new HashSet<Authors>();
        }
    
        public int Id { get; set; }
        public string ISBN10 { get; set; }
        public string ISBN13 { get; set; }
        public string Title { get; set; }
        public byte[] Cover { get; set; }
        public string Edition { get; set; }
        public int PublisherId { get; set; }
        public Nullable<System.DateTime> PublishedAt { get; set; }
        public System.DateTime ModifiedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Publishers Publishers { get; set; }
        public virtual ICollection<Authors> Authors { get; set; }
    }
}
